apiVersion: v1
kind: Pod
metadata:
  name: test-pod-sec
spec:
  containers:
  - image: mjbright/k8s-demo:alpine1
    name: test-container
    command: ['/bin/sh', '-c', 'while true; do cd /mnt/vol; ls -al; echo mike was here > new-key; ls -al; sleep 1; done']
    volumeMounts:
    - name: test-sec-vol
      mountPath: /mnt/vol
    
  volumes:
  - name: test-sec-vol
    secret:
      secretName: test-sec

