apiVersion: v1
kind: Pod
metadata:
  name: test-pod-cm
spec:
  containers:
  - image: mjbright/k8s-demo:alpine1
    name: test-container
    command: ['/bin/sh', '-c', 'cd /mnt/vol; ls -al; echo mike was here > new-key; ls -al']
    volumeMounts:
    - name: test-cm-vol
      mountPath: /mnt/vol
    
  volumes:
  - name: test-cm-vol
    configMap:
      name: test-cm

