apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: volume-test
    image: mjbright/k8s-demo:alpine1
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-c', 'while true; do echo "$(date): $(hostname) - looping ..." >> /data/date.log; sleep 1; done']
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: local-path-pvc
