
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-hp
spec:
  containers:

  - image: mjbright/k8s-demo:alpine1
    name: c1
    command: [ '/bin/sh', '-c', 'while true; do echo ${HOSTNAME}: $(date) >> /log.c1/date.log; sleep 1; done']
    volumeMounts:
    - mountPath: /log.c1
      name: log-volume

  volumes:
  - name: log-volume
    hostPath:
      path: "/tmp/log.c1"
  
