apiVersion: v1
kind: Pod
metadata:
  name: test-pod-ed
spec:

  containers:
  
  - image: mjbright/k8s-demo:alpine1
    name: test-ed
    command: [ '/bin/sh', '-c', 'date >> /log/date.log; cat /log/date.log; sleep 2']
    volumeMounts:
    - mountPath: /log
      name: log-volume
      
  volumes:
  - name: log-volume
    emptyDir: {}
