

apiVersion: v1
kind: Pod
metadata:
  name: pv-test

spec:
  restartPolicy: Never

  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc1
      readOnly: true

  containers:
  - name: pv-test
    image: mjbright/k8s-demo:alpine1
    command: ["/bin/sh", "-c", "while true; do echo cp: Mon Sep 26 16:34:29 UTC 2022 >> /cmount/date.log; sleep 1; done"]

    volumeMounts:
    - name: vol
      mountPath: /cmount
      
